language: python
python:
  - "3.5"
  - "3.6"
env:
  matrix:
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_script:
  - cat .tox/$TOX_ENV/log/*.log
